<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Astro implements JsonSerializable
{
    /**
     * Sunrise time
     * @var string|null $sunrise public property
     */
    public $sunrise;

    /**
     * Sunset time
     * @var string|null $sunset public property
     */
    public $sunset;

    /**
     * Moonrise time
     * @var string|null $moonrise public property
     */
    public $moonrise;

    /**
     * Moonset time
     * @var string|null $moonset public property
     */
    public $moonset;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $sunrise  Initialization value for $this->sunrise
     * @param string $sunset   Initialization value for $this->sunset
     * @param string $moonrise Initialization value for $this->moonrise
     * @param string $moonset  Initialization value for $this->moonset
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->sunrise  = func_get_arg(0);
            $this->sunset   = func_get_arg(1);
            $this->moonrise = func_get_arg(2);
            $this->moonset  = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['sunrise']  = $this->sunrise;
        $json['sunset']   = $this->sunset;
        $json['moonrise'] = $this->moonrise;
        $json['moonset']  = $this->moonset;

        return $json;
    }
}
