<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Astronomy implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Astro|null $astro public property
     */
    public $astro;

    /**
     * Constructor to set initial or default values of member properties
     * @param Astro $astro Initialization value for $this->astro
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->astro = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['astro'] = $this->astro;

        return $json;
    }
}
