<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Condition implements JsonSerializable
{
    /**
     * Weather condition text
     * @var string|null $text public property
     */
    public $text;

    /**
     * Weather icon url
     * @var string|null $icon public property
     */
    public $icon;

    /**
     * Weather condition unique code.
     * @var integer|null $code public property
     */
    public $code;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $text Initialization value for $this->text
     * @param string  $icon Initialization value for $this->icon
     * @param integer $code Initialization value for $this->code
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->text = func_get_arg(0);
            $this->icon = func_get_arg(1);
            $this->code = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['text'] = $this->text;
        $json['icon'] = $this->icon;
        $json['code'] = $this->code;

        return $json;
    }
}
