<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CurrentJsonResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Location|null $location public property
     */
    public $location;

    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Current|null $current public property
     */
    public $current;

    /**
     * Constructor to set initial or default values of member properties
     * @param Location $location Initialization value for $this->location
     * @param Current  $current  Initialization value for $this->current
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->location = func_get_arg(0);
            $this->current  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['location'] = $this->location;
        $json['current']  = $this->current;

        return $json;
    }
}
