<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Forecast implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Forecastday[]|null $forecastday public property
     */
    public $forecastday;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $forecastday Initialization value for $this->forecastday
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->forecastday = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['forecastday'] = $this->forecastday;

        return $json;
    }
}
