<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Forecastday implements JsonSerializable
{
    /**
     * Forecast date
     * @var string|null $date public property
     */
    public $date;

    /**
     * Forecast date as unix time.
     * @maps date_epoch
     * @var integer|null $dateEpoch public property
     */
    public $dateEpoch;

    /**
     * See day element
     * @var \WeatherAPILib\Models\Day|null $day public property
     */
    public $day;

    /**
     * @todo Write general description for this property
     * @var \WeatherAPILib\Models\Astro|null $astro public property
     */
    public $astro;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $date      Initialization value for $this->date
     * @param integer $dateEpoch Initialization value for $this->dateEpoch
     * @param Day     $day       Initialization value for $this->day
     * @param Astro   $astro     Initialization value for $this->astro
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->date      = func_get_arg(0);
            $this->dateEpoch = func_get_arg(1);
            $this->day       = func_get_arg(2);
            $this->astro     = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['date']       = $this->date;
        $json['date_epoch'] = $this->dateEpoch;
        $json['day']        = $this->day;
        $json['astro']      = $this->astro;

        return $json;
    }
}
