<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class IpJsonResponse implements JsonSerializable
{
    /**
     * IP address
     * @var string|null $ip public property
     */
    public $ip;

    /**
     * ipv4 or ipv6
     * @var string|null $type public property
     */
    public $type;

    /**
     * Continent code
     * @maps continent_code
     * @var string|null $continentCode public property
     */
    public $continentCode;

    /**
     * Continent name
     * @maps continent_name
     * @var string|null $continentName public property
     */
    public $continentName;

    /**
     * Country code
     * @maps country_code
     * @var string|null $countryCode public property
     */
    public $countryCode;

    /**
     * Name of country
     * @maps country_name
     * @var string|null $countryName public property
     */
    public $countryName;

    /**
     * true or false
     * @maps is_eu
     * @var bool|null $isEu public property
     */
    public $isEu;

    /**
     * Geoname ID
     * @maps geoname_id
     * @var integer|null $geonameId public property
     */
    public $geonameId;

    /**
     * City name
     * @var string|null $city public property
     */
    public $city;

    /**
     * Region name
     * @var string|null $region public property
     */
    public $region;

    /**
     * Latitude in decimal degree
     * @var double|null $lat public property
     */
    public $lat;

    /**
     * Longitude in decimal degree
     * @var double|null $lon public property
     */
    public $lon;

    /**
     * Time zone
     * @maps tz_id
     * @var string|null $tzId public property
     */
    public $tzId;

    /**
     * Local time as epoch
     * @maps localtime_epoch
     * @var integer|null $localtimeEpoch public property
     */
    public $localtimeEpoch;

    /**
     * Date and time
     * @var string|null $localtime public property
     */
    public $localtime;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $ip             Initialization value for $this->ip
     * @param string  $type           Initialization value for $this->type
     * @param string  $continentCode  Initialization value for $this->continentCode
     * @param string  $continentName  Initialization value for $this->continentName
     * @param string  $countryCode    Initialization value for $this->countryCode
     * @param string  $countryName    Initialization value for $this->countryName
     * @param bool    $isEu           Initialization value for $this->isEu
     * @param integer $geonameId      Initialization value for $this->geonameId
     * @param string  $city           Initialization value for $this->city
     * @param string  $region         Initialization value for $this->region
     * @param double  $lat            Initialization value for $this->lat
     * @param double  $lon            Initialization value for $this->lon
     * @param string  $tzId           Initialization value for $this->tzId
     * @param integer $localtimeEpoch Initialization value for $this->localtimeEpoch
     * @param string  $localtime      Initialization value for $this->localtime
     */
    public function __construct()
    {
        if (15 == func_num_args()) {
            $this->ip             = func_get_arg(0);
            $this->type           = func_get_arg(1);
            $this->continentCode  = func_get_arg(2);
            $this->continentName  = func_get_arg(3);
            $this->countryCode    = func_get_arg(4);
            $this->countryName    = func_get_arg(5);
            $this->isEu           = func_get_arg(6);
            $this->geonameId      = func_get_arg(7);
            $this->city           = func_get_arg(8);
            $this->region         = func_get_arg(9);
            $this->lat            = func_get_arg(10);
            $this->lon            = func_get_arg(11);
            $this->tzId           = func_get_arg(12);
            $this->localtimeEpoch = func_get_arg(13);
            $this->localtime      = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ip']              = $this->ip;
        $json['type']            = $this->type;
        $json['continent_code']  = $this->continentCode;
        $json['continent_name']  = $this->continentName;
        $json['country_code']    = $this->countryCode;
        $json['country_name']    = $this->countryName;
        $json['is_eu']           = $this->isEu;
        $json['geoname_id']      = $this->geonameId;
        $json['city']            = $this->city;
        $json['region']          = $this->region;
        $json['lat']             = $this->lat;
        $json['lon']             = $this->lon;
        $json['tz_id']           = $this->tzId;
        $json['localtime_epoch'] = $this->localtimeEpoch;
        $json['localtime']       = $this->localtime;

        return $json;
    }
}
