<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TimezoneJsonResponse implements JsonSerializable
{
    /**
     * Local area name.
     * @var string|null $name public property
     */
    public $name;

    /**
     * Local area region.
     * @var string|null $region public property
     */
    public $region;

    /**
     * Country
     * @var string|null $country public property
     */
    public $country;

    /**
     * Area latitude
     * @var double|null $lat public property
     */
    public $lat;

    /**
     * Area longitude
     * @var double|null $lon public property
     */
    public $lon;

    /**
     * Time zone
     * @maps tz_id
     * @var string|null $tzId public property
     */
    public $tzId;

    /**
     * Local date and time in unix time
     * @maps localtime_epoch
     * @var integer|null $localtimeEpoch public property
     */
    public $localtimeEpoch;

    /**
     * Local date and time
     * @var string|null $localtime public property
     */
    public $localtime;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name           Initialization value for $this->name
     * @param string  $region         Initialization value for $this->region
     * @param string  $country        Initialization value for $this->country
     * @param double  $lat            Initialization value for $this->lat
     * @param double  $lon            Initialization value for $this->lon
     * @param string  $tzId           Initialization value for $this->tzId
     * @param integer $localtimeEpoch Initialization value for $this->localtimeEpoch
     * @param string  $localtime      Initialization value for $this->localtime
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->name           = func_get_arg(0);
            $this->region         = func_get_arg(1);
            $this->country        = func_get_arg(2);
            $this->lat            = func_get_arg(3);
            $this->lon            = func_get_arg(4);
            $this->tzId           = func_get_arg(5);
            $this->localtimeEpoch = func_get_arg(6);
            $this->localtime      = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']            = $this->name;
        $json['region']          = $this->region;
        $json['country']         = $this->country;
        $json['lat']             = $this->lat;
        $json['lon']             = $this->lon;
        $json['tz_id']           = $this->tzId;
        $json['localtime_epoch'] = $this->localtimeEpoch;
        $json['localtime']       = $this->localtime;

        return $json;
    }
}
