<?php
/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WeatherAPILib;

use WeatherAPILib\Controllers;

/**
 * WeatherAPILib client class
 */
class WeatherAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $key = null
    ) {
        Configuration::$key = $key ? $key : Configuration::$key;
    }
    /**
     * Singleton access to APIs controller
     * @return Controllers\APIsController The *Singleton* instance
     */
    public function getAPIs()
    {
        return Controllers\APIsController::getInstance();
    }
}
